<a href="https://colab.research.google.com/github/annchirackal/PyTorch-Basics/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.5.1+cu121'

In [6]:
scalar= torch.tensor(7)
scalar+torch.tensor(7)

tensor(14)

In [7]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [11]:
vector=torch.tensor([4,5])

In [12]:
vector.ndim

1

In [18]:
vector

tensor([4, 5])

In [19]:
vector.itemsize

8

In [20]:
vector.shape

torch.Size([2])

In [21]:
tensor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [22]:
tensor.ndim

3

In [23]:
tensor.shape

torch.Size([1, 3, 3])

In [33]:
t=torch.tensor([[[1,2,4],[3,4,0]],[[3,2,8],[0,0,7]]])

In [34]:
t.ndim,t.shape

(3, torch.Size([2, 2, 3]))

In [35]:
## Suppose I own 3 grocery stores
#Apple,beetroot,carrot
## Apple (Gala,honey crisp,green apple)
## Beets(beets,organic, locally produced)
##Carrot(organic,with leaves, without levaes)
grocery_price=torch.tensor([[[1,2,3],[3,1,4],[3,2,1]],[[1,2,3],[2,2,1],[4,5,5]],[[3,2,1],[4,5,6],[5,4,6]]])

In [36]:
grocery_price.ndim,grocery_price.shape

(3, torch.Size([3, 3, 3]))

In [38]:
grocery_price[0][0]

tensor([1, 2, 3])

In [40]:
grocery_price[1][1]

tensor([2, 2, 1])

In [43]:
grocery_price[2][2]

tensor([5, 4, 6])

In [44]:
random_tensor=torch.rand(3,4)

In [45]:
random_tensor

tensor([[0.8958, 0.7713, 0.3949, 0.9745],
        [0.4681, 0.6788, 0.4833, 0.4170],
        [0.9932, 0.3605, 0.1889, 0.5743]])

In [46]:
random_image_size_tensor=torch.rand(size=(224,224,3))